service: "your-project"
awsAccountId: "Your-AWS-Acconnt-ID"
defaultRegion: "ap-northeast-1"
deploymentBucketName: "your-deployment"
cognitoJwtHeaderName: "Authorization"
cognitoJwtHeaderPrefix: "Bearer"

sesRegion: "us-west-2"
