domainName: your-project-api.example.com
corsAcceptOrigins: "https://prod.example.com,https://stg.example.com"
notificationEmail: admin@example.com
logsRestApiAccessLogging: true # Optional configuration which enables or disables access logging. Defaults to true.
logsRestApiExecutionLogging: true # Optional configuration which enables or disables execution logging. Defaults to true.
logsRestApiLevel: INFO # Optional configuration which specifies the log level to use for execution logging. May be set to either INFO or ERROR.
logsRestApiFullExecutionData: true # Optional configuration which specifies whether or not to log full requests/responses for execution logging. Defaults to true.
debugLogEnabled: false

wafName: pscms-api-acl # If use WAF, set existing Web ACL name. If set not existing name, ignore this.

appMemorySize: 256
appTimeout: 20 # s
appProvisionedConcurrency: 5

mediaS3BucketName: "media.example.com"
mediaDistributionId: "EXXXXXXXXXXXXXX"
mediaImageMakerMemorySize: 256 # MB
mediaImageMakerTimeout: 600 # s
mediaImageMakerFileSizeLimit: 20 # MB

mediaUnusedFilesCleanerMemorySize: 256 # MB
mediaUnusedFilesCleanerTimeout: 600 # s
mediaUnusedFilesCleanerReservedFileExpirationHours: 24 # Hours
mediaUnusedFilesCleanerEventSchedule: rate(1 day)

postDetailJsonGeneratorMemorySize: 128 # MB
postDetailJsonGeneratorTimeout: 300 # s

postStatusUpdater:
  memorySize: 128 # MB
  timeout: 600 # s
  eventSchedule: "cron(0/10 * * * ? *)" # Every 5 minutes

recaptcha:
  siteKey: ""
  secretKey: ""

commentDefaultPublishStatus: "unpublish"

# For Admin Console
cognitoRegion: "ap-northeast-1"
cognitoUserpoolId: "ap-northeast-1_*********"
cognitoAppClientId: "**************************"
cognitoCheckTokenExpiration: True # If set Falsae, disable token expiration checking for testing purposes

excludeFunctions:
  #- functions.mediaUnusedFilesCleaner
# excludeFunctions: [] # If not set exclude

dynamoDbBackupTargetTagValue: "aws-backup" # 'aws-backup':backup target / other value: not target
