Type: "AWS::DynamoDB::Table"
Properties:
  TableName: ${self:custom.prjPrefix}-contact
  AttributeDefinitions:
    - AttributeName: serviceId
      AttributeType: S
    - AttributeName: updatedAt
      AttributeType: S
    - AttributeName: serviceIdCode
      AttributeType: S
  KeySchema:
    - AttributeName: serviceIdCode
      KeyType: HASH

  BillingMode: ${self:custom.dynamodbConfig.contact.billingMode, 'PAY_PER_REQUEST'}
  ProvisionedThroughput:
    ReadCapacityUnits: ${self:custom.dynamodbConfig.contact.provisionedThroughput.readCapacityUnits, 0}
    WriteCapacityUnits: ${self:custom.dynamodbConfig.contact.provisionedThroughput.writeCapacityUnits, 0}

  Tags:
    - Key: backup
      Value: ${self:custom.dynamoDbBackupTargetTagValue}

  GlobalSecondaryIndexes:
    - IndexName: ${self:custom.prjPrefix}-contact-list-gsi
      KeySchema:
        - AttributeName: serviceId
          KeyType: HASH
        - AttributeName: updatedAt
          KeyType: RANGE
      Projection:
        ProjectionType: ALL
